### ISSUE TITLE
How to trigger the edit event manually?

### ISSUE THREAD

**Issue by openedhardware** [bymi15/react-edit-text#11]
I am using the following code to trigger the edit event manually:

```javascript
import React, { Component } from "react";
import 'react-edit-text/dist/index.css'
import { EditTextarea } from 'react-edit-text'

class NoteEditor extends Component {
  constructor(props) {
    super(props);
    this.noteRef = React.createRef();
  }
  onEditNote = () => {
    this.noteRef.current.click();
  }
  render() {
    return (
      <div>
        <EditTextarea ref={this.noteRef} value="Here is a sample note"/>
        <a className="text-primary" onClick={this.onEditNote}>Add/Edit</a>
      </div>
    );
  }
}
export default NoteEditor;
```

But it says that the `click()` is not a function. 
Is there any way to trigger the edit event manually?

**Comment by bymi15** [comment]
Hi,
I'm currently working on a new feature to allow displaying an Edit button which can be clicked on to enable edit mode.
This will also allow passing custom props to the edit button for customising and styling.
I'll let you know when this is complete and hopefully this should resolve your use case, instead of having to use refs and manually triggering the click function.
