### ISSUE TITLE
Would be handy if field could be focusable via tab button and then editable on enter

### ISSUE THREAD

**Issue by Jegard** [bymi15/react-edit-text#38]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ahmed-faraz46** [comment]
@bymi15 just faced a scenario where we are integrating hotkeys and landed on this already opened issue, slightly different from this request but relatable.

The scenario is whenever a user presses a particular key, let us say `m` we need to switch the text to editable mode, currently we are doing this by getting the reference of span and then triggering `.click()` on it and we have to trigger this click two times once on span and then after some timeout on the input to focus upon it.

Wondering if we can handle the edit and text modes via some prop(s) as well? 💭

**Comment by bymi15** [comment]
Hey @ahmed-faraz46,
This project was initially started with the concept of 'click-to-edit' and with the current structure i don't think it is possible to implement something like what you mentioned - to be able to toggle the component's editable mode externally via props (from outside the component) because the editable mode is being managed in the component's internal state.
The approach you mentioned: getting the reference and triggering .click() seems to be the best course of action.

Please feel free to let me know if you have any other opinions. Or you can also have a quick look at the src code as it is not too large - and see if there's some functionality that can be added to help with your use case.
Thanks.

**Comment by ahmed-faraz46** [comment]
Sure @bymi15, I'll have a look into the src code and let you know if I could think of any other solutions.
